//! This circuit is to check whether the output(c) is produced from the specific input(a,b, constant) under the arithmetic: `c = a^2 * b^2 * constant`,
//! Porting from halo2.

use halo2_proofs::{
    arithmetic::Field,
    circuit::{AssignedCell, Chip, Layouter, Region, SimpleFloorPlanner, Value},
    plonk::{Advice, Circuit, Column, ConstraintSystem, Error, Fixed, Instance, Selector},
    poly::Rotation,
};
use std::marker::PhantomData;

/// Chip state is stored in a config struct. This is generated by the chip
/// during configuration, and then stored inside the chip.
#[derive(Clone, Debug)]
struct MyCircuitConfig {
    // These are private input (advice) column
    pub(crate) a: Column<Advice>,
    pub(crate) b: Column<Advice>,
    // This is the public input (instance) column.
    pub(crate) c: Column<Instance>,
    // We need a selector to enable the multiplication gate.
    pub(crate) s_mul: Selector,
}

impl MyCircuitConfig {
    pub fn new<F: Field>(meta: &mut ConstraintSystem<F>) -> Self {
        // init the column.
        let a = meta.advice_column();
        let b = meta.advice_column();
        let c = meta.instance_column();
        let constant = meta.fixed_column();

        // enable ability of column.
        meta.enable_equality(a);
        meta.enable_equality(b);
        meta.enable_equality(c);
        meta.enable_constant(constant);

        let s_mul = meta.selector();

        // Define our multiplication gate!
        meta.create_gate("mul", |meta| {
            // To implement multiplication, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_mul |
            // |-----|-----|-------|
            // | lhs | rhs | s_mul |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(a, Rotation::cur());
            let rhs = meta.query_advice(b, Rotation::cur());
            let out = meta.query_advice(a, Rotation::next());
            let s_mul = meta.query_selector(s_mul);

            // Finally, we return the polynomial expressions that constrain this gate.
            // For our multiplication gate, we only need a single polynomial constraint.
            //
            // The polynomial expressions returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_mul = 0, any value is allowed in lhs, rhs, and out.
            // - When s_mul != 0, this constrains lhs * rhs = out.
            vec![s_mul * (lhs * rhs - out)]
        });

        MyCircuitConfig { a, b, c, s_mul }
    }
}

// A variable representing a number.
#[derive(Clone)]
struct Number<F: Field>(AssignedCell<F, F>);

// Circuit to check there are `a,b,constant` satisfy: `a^2 `* b^2 * constant == c".
// The private input: a, b, constant.
// The public input: c.
#[derive(Default)]
struct MyCircuit<F: Field> {
    constant: F,
    a: Value<F>,
    b: Value<F>,
}

impl<F: Field> MyCircuit<F> {
    fn load_private(
        &self,
        config: &MyCircuitConfig,
        mut layouter: impl Layouter<F>,
        value: Value<F>,
    ) -> Result<Number<F>, Error> {
        layouter.assign_region(
            || "load private",
            |mut region| {
                region
                    .assign_advice(|| "private input", config.a, 0, || value)
                    .map(Number)
            },
        )
    }

    fn load_constant(
        &self,
        config: &MyCircuitConfig,
        mut layouter: impl Layouter<F>,
        constant: F,
    ) -> Result<Number<F>, Error> {
        layouter.assign_region(
            || "load constant",
            |mut region| {
                region
                    .assign_advice_from_constant(|| "constant value", config.a, 0, constant)
                    .map(Number)
            },
        )
    }

    fn mul(
        &self,
        config: &MyCircuitConfig,
        mut layouter: impl Layouter<F>,
        a: Number<F>,
        b: Number<F>,
    ) -> Result<Number<F>, Error> {
        layouter.assign_region(
            || "mul",
            |mut region: Region<'_, F>| {
                // We only want to use a single multiplication gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                config.s_mul.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                a.0.copy_advice(|| "lhs", &mut region, config.a, 0)?;
                b.0.copy_advice(|| "rhs", &mut region, config.b, 0)?;

                // Now we can assign the multiplication result, which is to be assigned
                // into the output position.
                let value = a.0.value().copied() * b.0.value();

                // Finally, we do the assignment to the output, returning a
                // variable to be used in another part of the circuit.
                region
                    .assign_advice(|| "lhs * rhs", config.a, 1, || value)
                    .map(Number)
            },
        )
    }

    fn expose_public(
        &self,
        config: &MyCircuitConfig,
        mut layouter: impl Layouter<F>,
        num: Number<F>,
        row: usize,
    ) -> Result<(), Error> {
        layouter.constrain_instance(num.0.cell(), config.c, row)
    }
}

impl<F: Field> Circuit<F> for MyCircuit<F> {
    // Since we are using a single chip for everything, we can just reuse its config.
    type Config = MyCircuitConfig;
    type FloorPlanner = SimpleFloorPlanner;
    type Params = ();

    fn without_witnesses(&self) -> Self {
        Self::default()
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        Self::Config::new(meta)
    }

    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        // Load our private values into the circuit.
        let a = self.load_private(&config, layouter.namespace(|| "load a"), self.a)?;
        let b = self.load_private(&config, layouter.namespace(|| "load b"), self.b)?;

        // Load the constant factor into the circuit.
        let constant = self.load_constant(
            &config,
            layouter.namespace(|| "load constant"),
            self.constant,
        )?;

        // We only have access to plain multiplication.
        // We could implement our circuit as:
        //     asq  = a*a
        //     bsq  = b*b
        //     absq = asq*bsq
        //     c    = constant*asq*bsq
        //
        // but it's more efficient to implement it as:
        //     ab   = a*b
        //     absq = ab^2
        //     c    = constant*absq
        let ab = self.mul(&config, layouter.namespace(|| "a * b"), a, b)?;
        let absq = self.mul(&config, layouter.namespace(|| "ab * ab"), ab.clone(), ab)?;
        let c = self.mul(
            &config,
            layouter.namespace(|| "constant * absq"),
            constant,
            absq,
        )?;

        // Expose the result as a public input to the circuit.
        self.expose_public(&config, layouter.namespace(|| "expose c"), c, 0)
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use halo2_proofs::dev::MockProver;
    use halo2_proofs::halo2curves::pasta::Fp;
    use std::marker::PhantomData;

    #[test]
    fn test() {
        // ANCHOR: test-circuit
        // The number of rows in our circuit cannot exceed 2^k. Since our example
        // circuit is very small, we can pick a very small value here.
        let k = 4;

        // Prepare the private and public inputs to the circuit!
        let constant = Fp::from(7);
        let a = Fp::from(2);
        let b = Fp::from(3);
        let c = constant * a.square() * b.square();

        // Instantiate the circuit with the private inputs.
        let circuit = MyCircuit {
            constant,
            a: Value::known(a),
            b: Value::known(b),
        };

        // Arrange the public input. We expose the multiplication result in row 0
        // of the instance column, so we position it there in our public inputs.
        let mut public_inputs = vec![c];

        // Given the correct public input, our circuit will verify.
        let prover = MockProver::run(k, &circuit, vec![public_inputs.clone()]).unwrap();
        assert_eq!(prover.verify(), Ok(()));

        // If we try some other public input, the proof will fail!
        public_inputs[0] += Fp::one();
        let prover = MockProver::run(k, &circuit, vec![public_inputs]).unwrap();
        assert!(prover.verify().is_err());
        // ANCHOR_END: test-circuit
    }
}
